name: flutter_auth0
description: A Flutter plugin to use Auth0 authentication
author: Denny Segura <dev.dennysegura@gmail.com>
homepage: https://gitlab.com/tangerine_mobile/flutter_auth0.git
version: 0.2.1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  meta: ^1.0.4
  http: ^0.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.flutterauth0
    pluginClass: FlutterAuth0Plugin